name: Release Preview

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-(alpha|beta|rc)\.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --output .

      - name: Push LocalEnvVar.Core
        run: dotnet nuget push LocalEnvVar.Core.${VERSION}.nupkg --source https://nuget.pkg.github.com/stefan-karlsson/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push LocalEnvVar.Aws.Lambda
        run: dotnet nuget push LocalEnvVar.Aws.Lambda.${VERSION}.nupkg --source https://nuget.pkg.github.com/stefan-karlsson/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
