name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Verify commit exists in origin/main
        run: git branch --remote --contains | grep origin/main

      - name: Extract release notes
        run: |
          git log --pretty=format:'%d %s' ${GITHUB_REF} | sed -n 's/.*(tag: v\([0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-z]\+\([0-9]*\)\?\)\?\)).*/## \1/p' > RELEASE-NOTES

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output packages
      
      - name: Push
        run: dotnet nuget push packages/*.${VERSION}.nupkg --source https://nuget.pkg.github.com/stefan-karlsson/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.LIBRARY_RELEASE_TOKEN }}
